from __future__ import annotations

from typing import Any

TRANSLATIONS: dict[str, dict[str, str]] = {
    "ru": {
        "page_title": "Viva AI — адаптивный экзамен",
        "eyebrow": "Личный AI-экзаменатор",
        "hero_title": "Не перечитывайте. Проверяйте, что поняли.",
        "hero_body": "Загрузите материал, отвечайте своими словами и получите прозрачную оценку по каждому критерию.",
        "chip_grounded": "По вашему материалу",
        "chip_adaptive": "Адаптивные вопросы",
        "chip_private": "Локальная AI-модель",
        "settings": "Настройки",
        "language": "Язык",
        "model_mode": "Режим модели",
        "local_ollama": "Локальная Ollama",
        "cloud_api": "Облачный API",
        "local_model": "Локальная модель",
        "ollama_online": "Ollama подключена",
        "ollama_offline": "Ollama не отвечает. Запустите приложение Ollama.",
        "local_privacy": "Материалы остаются на этом компьютере.",
        "api_key": "API-ключ",
        "api_key_help": "Ключ используется только для выбранного API.",
        "base_url": "Base URL",
        "model": "Модель",
        "api_compatibility": "Поддерживается OpenAI-совместимый API.",
        "advanced_settings": "Расширенные настройки",
        "restart": "Начать заново",
        "material_title": "Выберите материал",
        "material_body": "Начните с демо или загрузите собственный конспект.",
        "demo_source": "Демо-конспект",
        "upload_source": "Свой файл",
        "demo_expander": "Что внутри демо",
        "demo_description": "Обучение с учителем, переобучение, метрики классификации и утечка данных.",
        "upload_label": "PDF, TXT или MD",
        "upload_help": "PDF должен содержать текстовый слой. До 10 МБ.",
        "file_too_large": "Файл больше 10 МБ.",
        "material_loaded": "Готово: {chars} символов",
        "start_title": "Короткий экзамен",
        "start_body": "5 адаптивных вопросов · прозрачная рубрика · персональный план",
        "start_button": "Начать экзамен",
        "exam_mode": "Формат",
        "quick_mode": "Quick · 3 вопроса",
        "full_mode": "Full · 5 вопросов",
        "difficulty": "Сложность",
        "difficulty_basic": "Базовая",
        "difficulty_standard": "Стандартная",
        "difficulty_advanced": "Продвинутая",
        "demo_instant": "Первый demo-вопрос откроется мгновенно.",
        "missing_key": "Введите API-ключ в боковой панели.",
        "how_title": "Как это работает",
        "how_1_title": "Материал",
        "how_1_body": "Viva AI выделяет темы и опирается только на источник.",
        "how_2_title": "Диалог",
        "how_2_body": "Следующий вопрос зависит от предыдущего ответа.",
        "how_3_title": "Разбор",
        "how_3_body": "Каждый балл объясняется через явные критерии.",
        "studying": "Изучаю материал и готовлю первый вопрос…",
        "progress": "Вопрос {current} из {total}",
        "material": "Материал",
        "session_label": "Сессия Viva",
        "source_context": "Контекст вопроса",
        "source_original": "Цитата сохранена на языке источника.",
        "completed": "Экзамен завершён",
        "completed_body": "Вот ваша персональная карта понимания материала.",
        "overall_score": "Итоговый результат",
        "topics_checked": "Проверено тем",
        "mastered": "Освоено",
        "needs_review": "Нужно повторить",
        "revision_plan": "План повторения",
        "details": "Подробные результаты",
        "repeat_tip": "Вернитесь к слабым темам и повторите опрос через 1–2 дня.",
        "mastery_map": "Карта освоения",
        "download_report": "Скачать отчёт Markdown",
        "new_exam": "Новый экзамен",
        "answer_label": "Ваш ответ",
        "answer_placeholder": "Объясните своими словами…",
        "check_answer": "Проверить ответ",
        "retry_answer": "Ответить ещё раз",
        "skip_question": "Пропустить",
        "finish_early": "Завершить сейчас",
        "skipped_feedback": "Вопрос пропущен.",
        "evaluating": "Сопоставляю ответ с критериями…",
        "score": "Оценка",
        "strengths": "Что получилось",
        "gaps": "Что дополнить",
        "breakdown": "Как рассчитана оценка",
        "status_met": "Выполнено",
        "status_partial": "Частично",
        "status_missing": "Не раскрыто",
        "answer_fragment": "Фрагмент ответа",
        "source": "Опора на материал",
        "show_summary": "Показать итог",
        "next_question": "Следующий вопрос",
        "adapting": "Адаптирую следующий вопрос…",
        "api_bad_key": "API отклонил ключ. Проверьте ключ и адрес.",
        "api_limit": "Лимит API исчерпан. Подождите или смените модель.",
        "api_error": "Ошибка API ({status}). Попробуйте ещё раз.",
        "api_timeout": "Модель не ответила вовремя. Попробуйте ещё раз.",
        "demo_name": "Основы машинного обучения",
    },
    "en": {
        "page_title": "Viva AI — adaptive oral exam",
        "eyebrow": "Your personal AI examiner",
        "hero_title": "Stop rereading. Start testing your understanding.",
        "hero_body": "Upload your material, answer in your own words, and get a transparent criterion-by-criterion assessment.",
        "chip_grounded": "Grounded in your material",
        "chip_adaptive": "Adaptive questions",
        "chip_private": "Local AI model",
        "settings": "Settings",
        "language": "Language",
        "model_mode": "Model mode",
        "local_ollama": "Local Ollama",
        "cloud_api": "Cloud API",
        "local_model": "Local model",
        "ollama_online": "Ollama connected",
        "ollama_offline": "Ollama is unavailable. Start the Ollama app.",
        "local_privacy": "Your material stays on this computer.",
        "api_key": "API key",
        "api_key_help": "The key is used only for the selected API.",
        "base_url": "Base URL",
        "model": "Model",
        "api_compatibility": "OpenAI-compatible APIs are supported.",
        "advanced_settings": "Advanced settings",
        "restart": "Start over",
        "material_title": "Choose your material",
        "material_body": "Try the demo or upload your own notes.",
        "demo_source": "Demo notes",
        "upload_source": "Upload file",
        "demo_expander": "What's in the demo",
        "demo_description": "Supervised learning, overfitting, classification metrics, and data leakage.",
        "upload_label": "PDF, TXT, or MD",
        "upload_help": "PDF must have a text layer. Up to 10 MB.",
        "file_too_large": "The file exceeds 10 MB.",
        "material_loaded": "Ready: {chars} characters",
        "start_title": "Short oral exam",
        "start_body": "5 adaptive questions · transparent rubric · personal study plan",
        "start_button": "Start the exam",
        "exam_mode": "Format",
        "quick_mode": "Quick · 3 questions",
        "full_mode": "Full · 5 questions",
        "difficulty": "Difficulty",
        "difficulty_basic": "Basic",
        "difficulty_standard": "Standard",
        "difficulty_advanced": "Advanced",
        "demo_instant": "The first demo question opens instantly.",
        "missing_key": "Enter an API key in the sidebar.",
        "how_title": "How it works",
        "how_1_title": "Material",
        "how_1_body": "Viva AI identifies topics and stays grounded in the source.",
        "how_2_title": "Dialogue",
        "how_2_body": "Each next question responds to your previous answer.",
        "how_3_title": "Breakdown",
        "how_3_body": "Every score is explained through explicit criteria.",
        "studying": "Reading the material and preparing your first question…",
        "progress": "Question {current} of {total}",
        "material": "Material",
        "session_label": "Viva session",
        "source_context": "Question context",
        "source_original": "Evidence is preserved in the source language.",
        "completed": "Exam complete",
        "completed_body": "Here is your personal map of the material.",
        "overall_score": "Overall score",
        "topics_checked": "Topics checked",
        "mastered": "Mastered",
        "needs_review": "Review next",
        "revision_plan": "Study plan",
        "details": "Detailed results",
        "repeat_tip": "Review weak topics and repeat the exam in 1–2 days.",
        "mastery_map": "Mastery map",
        "download_report": "Download Markdown report",
        "new_exam": "New exam",
        "answer_label": "Your answer",
        "answer_placeholder": "Explain it in your own words…",
        "check_answer": "Check answer",
        "retry_answer": "Try again",
        "skip_question": "Skip",
        "finish_early": "Finish now",
        "skipped_feedback": "Question skipped.",
        "evaluating": "Matching your answer against the rubric…",
        "score": "Score",
        "strengths": "What worked",
        "gaps": "What to improve",
        "breakdown": "How the score was calculated",
        "status_met": "Met",
        "status_partial": "Partial",
        "status_missing": "Missing",
        "answer_fragment": "Answer evidence",
        "source": "Source evidence",
        "show_summary": "View summary",
        "next_question": "Next question",
        "adapting": "Adapting the next question…",
        "api_bad_key": "The API rejected the key. Check the key and endpoint.",
        "api_limit": "API limit reached. Wait or choose another model.",
        "api_error": "API error ({status}). Please try again.",
        "api_timeout": "The model timed out. Please try again.",
        "demo_name": "Machine learning fundamentals",
    },
}


def text(language: str, key: str, **values: Any) -> str:
    template = TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, key)
    return template.format(**values)
